format = """
[](#242932)\
$conda\
$python\
$username\
[](bg:#2B303B fg:#242932)\
$directory\
[](fg:#2B303B bg:#343A46)\
$git_branch\
$git_status\
[](fg:#343A46 bg:#2B303B)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#2B303B bg:#2B303B)\
$docker_context\
[](fg:#2B303B bg:#2B303B)\
$time\
[ ](fg:#2B303B)\
"""

command_timeout = 5_000

[username]
show_always = true
style_user = "bg:#242932 fg:#ECEFF4"
style_root = "bg:#242932 fg:#BF616A"
format = "[ $user ]($style)"

[conda]
symbol = "🅒 "
style = "bg:#242932 fg:#A3BE8C"
format = "[ $symbol$environment ]($style)"
ignore_base = false

[python]
style = "bg:#242932 fg:#D8DEE9"
format = "[ ( $virtualenv) ]($style)"

[directory]
style = "bg:#2B303B fg:#ECEFF4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
symbol = " "
style = "bg:#343A46 fg:#ECEFF4"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#343A46 fg:#D8DEE9"
format = "[ $all_status$ahead_behind ]($style)"

[c]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[elixir]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[elm]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[haskell]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[julia]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[nim]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = " "
style = "bg:#2B303B fg:#81A1C1"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = " "
style = "bg:#2B303B fg:#88C0D0"
format = "[ $symbol $context ]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#2B303B fg:#D8DEE9"
format = "[ $time ]($style)"
