format = """
[](#181825)\
$conda\
$python\
$username\
[](bg:#313244 fg:#181825)\
$directory\
[](fg:#313244 bg:#45475a)\
$git_branch\
$git_status\
[](fg:#45475a bg:#313244)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#313244 bg:#313244)\
$docker_context\
[](fg:#313244 bg:#313244)\
$time\
[ ](fg:#313244)\
"""
command_timeout = 5_000

[username]
show_always = true
style_user = "bg:#181825 fg:#cdd6f4"
style_root = "bg:#181825 fg:#f38ba8"
format = "[ $user ]($style)"

[conda]
symbol = "🅒 "
style = "bg:#181825 fg:#a6e3a1"
format = "[ $symbol$environment ]($style)"
ignore_base = false

[python]
style = "bg:#181825 fg:#a6adc8"
format = "[ ( $virtualenv) ]($style)"

[directory]
style = "bg:#313244 fg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

  [directory.substitutions]
  Documents = "󰈙 "
  Downloads = " "
  Music = " "
  Pictures = " "

[git_branch]
symbol = " "
style = "bg:#45475a fg:#cdd6f4"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#45475a fg:#a6adc8"
format = "[ $all_status$ahead_behind ]($style)"

[c]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[elixir]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[elm]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[haskell]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[julia]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[nim]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = " "
style = "bg:#313244 fg:#b4befe"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = " "
style = "bg:#313244 fg:#94e2d5"
format = "[ $symbol $context ]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#313244 fg:#a6adc8"
format = "[ $time ]($style)"
