color0 #4f434e
color1 #ffb4ab
color2 #f6adff
color3 #e1bae3
color4 #ffb1bf
color5 #f6adff
color6 #e1bae3
color7 #ebdfe7
color8 #9b8c99
color9 #ffb4ab
color10 #f6adff
color11 #e1bae3
color12 #ffb1bf
color13 #f6adff
color14 #e1bae3
color15 #ebdfe7

cursor                #ebdfe7
cursor_text_color     #171217
background            #171217
foreground            #ebdfe7
selection_foreground  #d2c2d0
selection_background  #4f434e
active_border_color   #f6adff
inactive_border_color #4f434e
url_color             #f6adff

active_tab_foreground   #540a64
active_tab_background   #f6adff
inactive_tab_foreground #d2c2d0
inactive_tab_background #4f434e
cursor_trail_color      #d2c2d0
